### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by probonopd**
Paths and variable names have been changed recently but the documentation has not been updated.

While we are at it, why not also document how to use Docker interactively, right above the line

> This whole process takes only a few seconds, e.g., on GitHub Codespaces.

```
If you would like to use Docker instead of chroot, the following will build the contents of this repository in an Alpine container:
...
````

What exactly to write there @TheAssassin?

### CODE REVIEW

**Comment by TheAssassin** [comment]
You don't seem to have seen https://github.com/AppImage/type2-runtime/blob/main/BUILD.md yet. Please have a look.

**Comment by probonopd** [comment]
Indeed. Let's mention it. Please review. Thanks!

**Comment by andy5995** [comment]
> You don't seem to have seen https://github.com/AppImage/type2-runtime/blob/main/BUILD.md yet. Please have a look.

@probonopd Some of the paths mentioned in BUILD.md are incorrect. These are now in scripts/docker/.

```
scripts/build-with-docker.sh
scripts/create-build-container.sh
```

Also, this section has the same example for building an AppImage, but the heading is Interactive Environment.

https://github.com/AppImage/type2-runtime/blob/main/BUILD.md#interactive-environment

**Comment by probonopd** [comment]
Ping @TheAssassin

**Review by TheAssassin — APPROVED** [review]

**Pull request merged**
