### PR TITLE
Fix chroot builds fail to copy out binaries

### LINKED ISSUE #77: chroot builds fail to copy out binaries
I tried chroot build, because I use Slackware 15.0 i586 so docker is unsupported here.

First, build need ALPINE_ARCH, documentation in BUILDING wrong on this point.

Second, it failed to produce binaries in "out" when run like this:

env ALPINE_ARCH=x86 scripts/chroot/chroot_build.sh

I think I fixed that, see attach
[0001-Fix-chroot-build-so-it-copies-out-binaries.txt](https://github.com/user-attachments/files/17446881/0001-Fix-chroot-build-so-it-copies-out-binaries.txt)

basically just use "runtime-${appimage_arch}" instead of plain 'runtime' in find lines.

### PR DESCRIPTION
**Pull request by probonopd**
Closes #77; thanks @Randrianasulu

### CODE REVIEW

**Comment by TheAssassin** [comment]
Looks good to me. Would you mind fixing the (unrelated) build failure by changing a `2` for a `4` in the artifacts action?

**Review by TheAssassin — APPROVED** [review]

**Comment by probonopd** [comment]
With v4 it does not work. Hence downgrading again.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 1[9](https://github.com/AppImage/type2-runtime/actions/runs/11427873502/job/31792563805?pr=78#step:4:10)8, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/appimage_extracted_556096427a8a96a78afb7e0fd53896f2/usr/conda/lib/python3.[11](https://github.com/AppImage/type2-runtime/actions/runs/11427873502/job/31792563805?pr=78#step:4:12)/site-packages/pyuploadtool/__main__.py", line 31, in <module>
    raise FileNotFoundError(artifact)
FileNotFoundError: artifacts/*
```

**Comment by Randrianasulu** [comment]
> Now we get
> 
> > Error: This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> 
> I don't know how to fix this, or how to merge this PR. The old v2 used to work, v4 throws an error, and downgrading this PR doesn't seem to be possible. Any idea @TheAssassin?

----

any relevant info there?

https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes

it says v4 fails to download artefacts created by upload artefacts v3 and below ?

**Comment by TheAssassin** [comment]
We've had similar issues in some other repository. I'll try to fix the issue.

**Pull request merged**
