### PR TITLE
Simplify build process and add runtime-fuse3 build

### PR DESCRIPTION
**Pull request by lalten**
* Adds a new CI build matrix option to build with Fuse3 instead of Fuse2
* Uses a fork of the run-on-arch-action GitHub Action that allows simplifying the amd64 and i386 builds (chroot_build.sh is not needed anymore)
* Update readme with easier instruction to build
* Cleanup after the build and add .gitignore for artifacts

See also https://github.com/probonopd/static-tools/pull/30

Example of `continuous` release Artifacts: https://github.com/lalten/type2-runtime/releases/tag/continuous

### CODE REVIEW

**Comment by probonopd** [comment]
Hi @lalten, why would we want different versions of the runtime?

**Comment by lalten** [comment]
Wasn't that the point of https://github.com/probonopd/static-tools/pull/30?
I'm not sure it would be feasible to include both the fuse2 and fuse3 runtime.

**Comment by probonopd** [comment]
We are statically linking, which means that a runtime that statically links libfuse can run on systems regardless whether the ship libfuse2 or libfuse3, as long as they ship a compatible version of `fusermount`.

**Comment by lalten** [comment]
> as long as they ship a compatible version of fusermount

Right, doesn't that mean that for now there are still two separate runtimes required that cater for the difference between `fusermount` and `fusermount3`?

**Comment by probonopd** [comment]
Luckily no. We just need to make sure that the runtime tries `fusermount`, `fusermount2`. `fusermount3` .... `fusermountN`.

**Comment by lalten** [comment]
Does the runtime actually call fusermout itself? My understanding was that the mounting happens in https://github.com/AppImage/type2-runtime/blob/813aa681e88300e6089f0b55c9a3161c420ae166/src/runtime/runtime.c#L982, which is selected at compile time for either fuse2 or fuse3: https://github.com/vasi/squashfuse/blob/0.1.105/ll.c#L396

**Comment by lalten** [comment]
https://github.com/vasi/squashfuse/issues/60 is also relevant here. I like @vasi's idea of somehow including two versions of squashfuse and choosing at runtime.

**Comment by probonopd** [comment]
Unneeded complication?

**Comment by lalten** [comment]
Well, if it allows running the same appimage on systems with fuse2/fusermont and fuse3/fusermount3, that would be a win, no?

I see https://github.com/AppImage/AppImageKit/issues/1120 is also discussing this topic.

**Comment by lalten** [comment]
Looks like statically linking both a fuse2 and fuse3 version of squashfuse_ll is possible using the technique described in https://stackoverflow.com/a/6940389/5559867

**Comment by lalten** [comment]
I would suggest to merge this PR to enable downstream appimage users who have only fuse3 installed (while existing users of the fuse2-version runtime will remain unaffected); and I can have a look at wrapping the two versions of squashfuse_ll and make a separate PR that will unify the runtime variants.

**Comment by lalten** [comment]
I had a stab at it. You can find the WIP in https://github.com/lalten/type2-runtime/compare/add-fuse3-version...lalten:type2-runtime:runtime-squashfs-variant-switch.
It's possible to include the #define-switched parts of squashfuse twice as described. However I have the feeling that for some reason sqfs seems to still call into fuse3 which has fusermount3 hardcoded. There is no good matching error message though, it seems like everything works, only the mount point is not populated :/
```
❯ cat out/runtime-x86_64 test.sqfs > test.ai && chmod +x test.ai && ./test.ai
fuse: failed to exec fusermount3: No such file or directory
sqfs_ll_mount failed (Operation not permitted), trying f2_sqfs_ll_mount... ok
/tmp/.mount_test.agFgEIO/AppRun does not exist
```

**Comment by lalten** [comment]
I tried an alternative approach: if `fusermount3` is not on $PATH, create a symlink to `fusermount` called `fusermount3` in a temp dir and place that on path just before asking libfuse to mount.
By doing this, only the fuse3 variant of squashfuse is needed.
See https://github.com/lalten/type2-runtime/compare/add-fuse3-version...lalten:type2-runtime:symlink-fusermount

**Comment by probonopd** [comment]
Having more than one libfuse doubles the maintenance burden and size, so it is not something we should do. Instead, we should patch it so that it tries (in this order)
* fusermount
* fusermount2
* fusermount3
* ...
* fusermount99

**Comment by probonopd** [comment]
> no other fusermount versions exist
...unless some distribution out there is doing wild things...

We don't want to litter the filesystem outside of our mountpoint, as it'd get very messy very quickly when the user is running multiple AppImages and/or multiple instances of the same AppImage.

**Comment by lalten** [comment]
See the diff in https://github.com/AppImage/type2-runtime/pull/3#issuecomment-1264785902, it's happening in a unique-per-run tempdir that is cleaned up right after.

**Comment by probonopd** [comment]
Build system has changed since; this is no longer applicable. Thank you nevertheless for your contribution @lalten.

**Pull request closed without merging**
