### PR TITLE
Enable portable home/config dirs for extract-and-run

### PR DESCRIPTION
**Pull request by xordspar0**
Backported from https://github.com/AppImage/AppImageKit/pull/1247

### CODE REVIEW

**Comment by xordspar0** [comment]
The build fails on Alpine 3.17+ because zstd-static no longer exists; it was merged into zstd-dev. It's trivial to fix this and make both the chroot and qemu builds use Alpine 3.17, but maybe it's better to stick to an older release of Alpine in case a newer musl starts depending on new kernel features?

**Comment by xordspar0** [comment]
> maybe it's better to stick to an older release of Alpine

Hm, `run-on-arch-action`, used for the qemu build, only supports alpine_latest. In that case I will update the build to work with Alpine 3.17 unless I can find a different way to cross compile with qemu.

**Comment by probonopd** [comment]
@TheAssassin wdyt?

**Comment by xordspar0** [comment]
@probonopd, Does TheAssassin know to check for pull requests on this repo? It looks like he hasn't contributed to or reviewed PRs on type2-runtime before.

**Comment by probonopd** [comment]
I'd assume he is just busy with other things; in general he knows this repository :-)

**Comment by probonopd** [comment]
Friendly ping @TheAssassin - maybe you can have a look at this when you have some time (says the guy who hasn't enough time, most of the time).

**Comment by probonopd** [comment]
Ready for merging @TheAssassin?

**Review by TheAssassin — APPROVED** [review]

**Comment by xordspar0** [comment]
Yay, thank you!

**Pull request merged**
