### PR TITLE
Build with docker_platform=linux/arm/v6 to support RPi 1

### PR DESCRIPTION
**Pull request by probonopd**
Closes https://github.com/AppImage/type2-runtime/issues/112

### CODE REVIEW

**Comment by probonopd** [comment]
Confirmed to fix the issue in https://github.com/AppImage/type2-runtime/issues/112#issuecomment-2556861908 by @mediocregopher. Still to be retested on e.g., a Pi 2 in 32-bit mode, although I would assume that people use aarch64 there.

**Comment by TheAssassin** [comment]
As far as I remember, ARMv6 binaries have a significant performance disadvantage on ARMv7, so that would need to be evaluated.

On the other hand, RPi v1 chips are really ancient and distro support is going to end at some point just like with i386.

**Comment by TheAssassin** [comment]
See also https://github.com/AppImage/type2-runtime/issues/112#issuecomment-2557669479, I'm not sure that this change makes Debian i386 provide ARMv6 compatible binaries.

**Comment by probonopd** [comment]
Moreover, iirc everything newer than RPi1 is 64-bit. So the _only_ reason for the 32 bit builds is essentially RPi 1. So better a bit slower than not working at all, I'd say.

**Comment by TheAssassin** [comment]
We're not talking just about RPi 1 when talking about 32-bit ARM platforms. RPi 1 is the _only_ ARMv6 platform I know of, though. It's using a chip that is around 20 years old, I think they chose to do so because of integration problems or licensing or so. But yes, the vast majority of boards nowadays uses 64-bit, ARMv8 has been around for a while. Many phones or so for instance are ARMv7 for example. So it makes sense to at least try the 32-bit performance on an ARMv7 platform.

I might look around to see if I can find some. Given the above, though, I'm not sure if this shouldn't be a special build for special needs. There's no point in shipping an ARMv6 compatible runtime if all the payload applications are incompatible, for instance.

**Comment by mediocregopher** [comment]
@TheAssassin responding to [your comment in the issue](https://github.com/AppImage/type2-runtime/issues/112#issuecomment-2557669479): I can confirm that the payload here does work on my RPI 1.

> Build for testing: [artifacts x86_64](https://github.com/AppImage/type2-runtime/suites/32305023443/artifacts/2348107431) [artifacts i686](https://github.com/AppImage/type2-runtime/suites/32305023443/artifacts/2348108067) [artifacts armhf](https://github.com/AppImage/type2-runtime/suites/32305023443/artifacts/2348124321) [artifacts aarch64](https://github.com/AppImage/type2-runtime/suites/32305023443/artifacts/2348126432) Use at your own risk.

If supporting RP1 isn't a priority I totally understand that, I had just asked to confirm that was the case. I'm already able to package my application using debian and pacman package files, AppImage would be a bonus but it's not a hard requirement for me.

**Comment by probonopd** [comment]
I would like to keep support for Raspberry Pi 1.

**Comment by TheAssassin** [comment]
> keep

Again: we have not supported ARMv6 for years.

**Comment by probonopd** [comment]
But always intended to. It was a bug that this PR fixes.

**Comment by TheAssassin** [comment]
I would like to see a performance comparison nevertheless. But if you insist, go for it.

**Review by TheAssassin — APPROVED** [review]

**Comment by probonopd** [comment]
Let's roll back if anyone ever complains about performance on 32-bit ARM.

**Pull request merged**
