### PR TITLE
Trigger appimagetool build

### PR DESCRIPTION
**Pull request by probonopd**
Try to trigger an appimagetool build in addition to uploading the continuous build to GitHub Releases.

Thus, when a change in this repository prevents the appimagetool AppImage from being built correctly, we will know immediately rather than a few months down the line.

This in part might have prevented

* https://github.com/AppImage/appimagetool/issues/58

from having happened unnoticed.

### CODE REVIEW

**Comment by probonopd** [comment]
> TypeError: Cannot read properties of undefined (reading 'token')

How to do this correctly?

**Comment by TheAssassin** [comment]
We've talked about this recently and I absolutely hate the idea. Plus, the token you try to use isn't even authorized to do so.

appimagetool automatically downloads the latest runtime anyway.

**Comment by probonopd** [comment]
> We've talked about this recently and I absolutely hate the idea.

Can you remind me of why you don't like this? Maybe combining the repos of type2-runtime and appimagetool would be a more elegant solution then?

> appimagetool automatically downloads the latest runtime anyway.

Which is what I still think is too fragile, especially when the two are not in sync (which can happen due to developer error or simply because the user uses an older appimagetool version...)

**Comment by TheAssassin** [comment]
> Maybe combining the repos of type2-runtime and appimagetool would be a more elegant solution then?

Yet again, discussed and rejected. That's what we had, and it's what we never want to go back to.

**Comment by TheAssassin** [comment]
You should open an issue by the way.

**Comment by probonopd** [comment]
> You should open an issue by the way.

For what? Everything I propose doesn't seem to be liked by you (triggering builds in another repo automatically, merging repos). For bundling the runtime in the linudeployqt AppImage there is already an issue open,

* https://github.com/AppImage/appimagetool/issues/61

**Comment by TheAssassin** [comment]
The issue here is that this discussion is likely going to be lost in a closed PR.

> Everything I propose doesn't seem to be liked by you

We've discussed every single option and I've always had the better arguments after all. It's tiring to reiterate over each of them every time some issue surfaces. It's nothing I'd do in a project because it's not productive.

It seems that the issue here is missing documentation from meetings we had...

**Pull request closed without merging**
