### PR TITLE
Suggest to bump alpine release to latest known today: 3.21.0.

### PR DESCRIPTION
**Pull request by rubisher**
Hello all,
I am not namely a developer (more a sysadmin) but very interested to understand how AppImage works in details.
As I am trying to rebuild on my own this 'runtime', that Alpine base can be upgraded to take benefit of improvement (perf, security, ...).
For the moment, I am only able to test this build with the proposed Vagrantfile virtualbox VM (release 7.0.22) with chroot method and seems to complete with success (eventhought I don't know yet how to actually test it in an AppImage :()
Tia for kind attention, take care,
Rudy.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Haven't tried it, but it looks good. Feel free to merge.

**Comment by TheAssassin** [comment]
P.S.: We could parse the Dockerfile's header from these scripts to keep things in sync. Also, I think there already is a separate script for dependency installation, we may want to share those resources as well. (Even though I still think that maintaining two build systems is not a great idea, and I don't take any responsibility for the chroot script.)

**Comment by TheAssassin** [comment]
@rubisher by the way, is there a reason you're not using Docker? I mean, it's good to keep things in sync. Just curious.

**Comment by rubisher** [comment]
Hello @TheAssassin,
I initially attempted to build this 'runtime' using Docker, but I encountered issues I couldn't resolve right away due to my limited familiarity with Docker (I only understand the basics for now). Since my primary goal was to reconstruct what I see as the 'kernel' of AppImage, I decided to try the chroot method instead. Its success encouraged me to continue progressing.
I will try again with docker asap.
Thx a lot for advises,
Rudy

**Pull request merged**
