### PR TITLE
Fix --appimage-version

### LINKED ISSUE #103: --appimage-version is empty
As [noticed](https://github.com/AppImage/appimagetool/issues/80#issuecomment-2525082837) by @brunvonlope:

Running `--appimage-version` in appimages generated by appimagetool gives **no** output:

`AppImage runtime version: `

### PR DESCRIPTION
**Pull request by probonopd**
Closes #103

### CODE REVIEW

**Comment by probonopd** [comment]
Works!

```
$ ./runtime-x86_64 --appimage-version
AppImage runtime version: https://github.com/AppImage/type2-runtime/commit/27bf5f4
```

**Comment by TheAssassin** [comment]
None of the commands after your export call picks it up. How could it possibly work?

**Comment by probonopd** [comment]
Why does it work then?

**Review by TheAssassin — CHANGES_REQUESTED** [review]
Please move into Makefile so that it is truly standalone

**Review by TheAssassin — APPROVED** [review]

**Comment by probonopd** [comment]
Thanks @TheAssassin for the cleaner solution in the Makefile

**Pull request merged**
