### PR TITLE
Remove superfluous -type3 suffix from artifacts

### PR DESCRIPTION
**Pull request by TheAssassin**
fuse2 is no longer supported. I also fixed a few oversights from its removal.

Fixes https://github.com/AppImage/appimagetool/issues/58.

### CODE REVIEW

**Comment by probonopd** [comment]
While I agree that the suffix should be removed, https://github.com/AppImage/appimagetool/commit/993b8c38905f1cc6a644e04648e61d67415a29ec would need to be reverted then as well. These things must currently be done in sync or everything will break (like it was this morning).

**Review by probonopd — APPROVED** [review]

**Comment by TheAssassin** [comment]
Please stop randomly pushing without reviews.

**Comment by probonopd** [comment]
I have reviewed this, then merged it.

**Comment by probonopd** [comment]
Since i have merged this, I also have to merge https://github.com/AppImage/appimagetool/pull/62 without delay, or else appimagetool will be in a broken state.

**Comment by TheAssassin** [comment]
I was referring to your PR in appimagetool. I'm still trying to figure out the slight mess created today while I was at work.

As said before, we can add tests accordingly. Triggering builds randomly across repositories is insufficient and doesn't really test what we want to know. Also, it unnecessarily delays the build process.

**Comment by probonopd** [comment]
> Triggering builds

Let's discuss that topic in
* https://github.com/AppImage/type2-runtime/pull/50

**Pull request merged**
